apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: strange-radha-3367b5d70b-hc
  namespace: apps-release
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 7070
        requestPath: /docs
  targetRef:
    group: ""
    kind: Service
    name: strange-radha-3367b5d70b-srv
