apiVersion: v1
kind: Service
metadata:
  name: strange-radha-3367b5d70b-srv
  namespace: apps-release
spec:
  selector:
    app: strange-radha-3367b5d70b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP